//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarefas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int ID_Tarefa { get; set; }
        public System.DateTime Data { get; set; }
        public string Titulo { get; set; }
        public string Nota { get; set; }
        public bool Lido { get; set; }
    }
}
